name = "Bats"
grammar = "bats"
code_fence_block_name = "bats"
path_suffixes = ["bats"]
first_line_pattern = '^#!.*\bbats\b'
line_comments = ["# "]
autoclose_before = ";)]}"
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = false },
  { start = "(", end = ")", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["comment", "string"] },
  { start = "'", end = "'", close = true, newline = false, not_in = ["comment", "string"] },
]
decrease_indent_pattern = '^\s*(elif|else)\b'
tab_size = 2
